### PR TITLE
Fix CSS rule storage, new button

### PR DESCRIPTION
**Pull request by Icebird**
I've done three things in this update:

1. Fixed the bug where CSS rules get scrambled when you restart your browser due to Chrome storage not reliably storing objects directly.
2. Added a 'Save & Close' button to the Edit CSS modal view which saves changes and closes the stylebot sidebar.
3. Modified the behavior of the Cancel button **only when Edit CSS is the default view** to close the stylebot sidebar without saving changes (instead of returning to the Basic/Advanced views).

### CODE REVIEW

**Comment by wmertens** [comment]
@Icebird This project is obviously abandoned, so maybe you want to publish your fork as a new chrome extension? I would use it :)

**Comment by Icebird** [comment]
@wmertens I will look into that, thanks!

**Comment by Icebird** [comment]
@wmertens How's this? [Stylebot Lite](https://chrome.google.com/webstore/detail/stylebot-lite/lkcdgdbfbbnpnljlalmcjnepgjnmgigh)

**Comment by sdphm80** [comment]
Thanks @Icebird  for starting up this project again! I love this tool, but without updates it is behind. If I might suggest a feature - It would be nice to have data save to the users cloud storage as an option.

**Comment by ankit** [comment]
Just an update, I am working on a new release which will address a lot of the issues that came up in the past and make the code a lot more maintainable

**Pull request closed without merging**
