### PR TITLE
Improve Usability at Options page.

### PR DESCRIPTION
**Pull request by sika-uma**

### CODE REVIEW

**Comment by JonasNo** [comment]
In what way do this improve it? Can't tell based on file changes.

**Comment by benvan** [comment]
It allows users to toggle styles on and off by clicking on the url for that style in options>styles>styles.
Currently you can only toggle styles on and off by clicking on the checkbox itself.

**Comment by wmertens** [comment]
👍 @ankit

**Comment by ankit** [comment]
@sika-uma sorry for never responding, but I finally manually applied your patch. will be in a release soon

**Comment by ankit** [comment]
Manually merged in https://github.com/ankit/stylebot/commit/9adbf82ce43f03ddba6791cfa89705f98440cb48

**Pull request closed without merging**
